### ISSUE TITLE
no longer pulls correctly via ansible galaxy command

### ISSUE THREAD

**Issue by phreddrick** [ahuffman/ansible-resolv#5]
The command in the documentation to pull this role from ansible galaxy no longer works correctly, because it is trying to pull version v1.2.tar.gz which doesn't exist. 
```bash
ansible-galaxy install ahuffman.resolv
- downloading role 'resolv', owned by ahuffman
- downloading role from https://github.com/ahuffman/ansible-resolv/archive/v1.2.tar.gz
 [ERROR]: failed to download the file: HTTP Error 404: Not Found

 [WARNING]: - ahuffman.resolv was NOT installed successfully.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by JohnGarbutt** [comment]
I have moved to use 1.3.1, in case that helps. v1.2 has just stopped downloading for me too.

**Comment by ahuffman** [comment]
@phreddrick @JohnGarbutt Thanks for notifying me.  I noticed a problem yesterday and that even though there was a newer release out (1.3.1), it was still installing v1.2 tag which is pretty old from Galaxy and was incorrect.  I tried dropping the old releases to see if that would fix the Galaxy latest version issue.  It did not.  Then I had an issue reimporting the role to see if that would fix it, and opened an issue on the ansible/galaxy repo.  It turns out my auth session with Galaxy had timed out and a logout/login allowed me to reimport the repository into Galaxy this morning.  I verified this is resolved as of now.  `ansible-galaxy install ahuffman.resolv` will not install the latest version 1.3.1 as expected.  Sorry for any inconveniences everyone!  Thanks again for reporting.
